Feature/ab2d 3825 introduce sqs localstack
CMSgov/ab2d pull request #1010
Opened 2022-05-04 16:26 UTC by sb-keane

**JIRA Tickets:**

[AB2D-42](https://jira.cms.gov/browse/AB2D-3825) - Description

Adjust job tracking to use SQS queue. In-memory tracking still works. SQS can be enabled by changing a feature flag. 
 
### What Does This PR Do?

1. Adds an SQS path for job tracking
2. New property to enable using SQS 
3. Initial localstack unit test integration 
4. Provides support for using SQS locally 

### What Should Reviewers Watch For?
Issues when running this on multiple nodes 

### Usage/Deployment Instructions
Running locally:
Uncomment the localstack service in docker-compose.tml
docker compose up localstack 
add these VM options to worker:
```
 -Dlocalstack=127.0.0.1:4566 to the VM options of worker
 -Dcloud.aws.region.static=us-east-1
 -Dcom.amazonaws.sdk.disableCertChecking
```

### Impacted External Components

### Database Changes
INSERT INTO properties (id, key, value) VALUES((select nextval('hibernate_sequence')), 'sqs_job_update.engaged', 'idle');

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [X] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [X] Code checked for PHI/PII exposure

2022-06-15 20:27 UTC, sharshar-sb requested changes

2022-06-15 20:51 UTC, nflearl approved these changes

2022-06-15 20:51 UTC, nflearl commented on worker/src/main/java/gov/cms/ab2d/worker/service/JobUpdateListenerServiceImpl.java
> +                });
In general, I think refactoring to method makes code like this clearer.  The method then has a name and the code within pollJobUpdateSqs states at the same level of abstraction.

2022-06-15 20:52 UTC, nflearl commented on e2e-bfd-test/src/test/java/gov/cms/ab2d/testjobs/EndToEndBfdTests.java
> +import gov.cms.ab2d.worker.processor.coverage.*;
Nice catch, I missed that.

2022-06-16 21:49 UTC, nflearl approved these changes

2023-03-01 16:09 UTC, closed without merging