Dependabot/maven/aws react jwt assembly GitHub
CMSgov/ab2d pull request #1063
Opened 2022-07-21 19:27 UTC by sb-keane

**JIRA Tickets:**

[AB2D-42](https://jira.cms.gov/browse/AB2D-4823) - Description
Combine dependabot PRs and test them. 

### What Does This PR Do?
Combines these PRs
https://github.com/CMSgov/ab2d/pull/1062
https://github.com/CMSgov/ab2d/pull/1060
https://github.com/CMSgov/ab2d/pull/1059
https://github.com/CMSgov/ab2d/pull/1051

Revert docker compose file version to 2.4 to fix errors caused by the us of deprecated features. 

**Revert api and worker java docker image from openjdk:19 back to openjdk:17. 
openjdk:17 has a few more security issues but New Relic doesn't work with 19 yet.** 

### What Should Reviewers Watch For?

Unintended issues for individual local environments. 

### Usage/Deployment Instructions

### Impacted External Components

### Database Changes

- [ ] All QuickSight impacts have been identified

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [X] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [X] Code checked for PHI/PII exposure

2022-07-21 19:37 UTC, sb-keane commented on docker-compose.yml
> +version: '2.4'
Docker deprecated depend_on ->service -> condition in v3. There is a replacement but that only works with swarms. 
https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on

2022-07-21 19:39 UTC, sb-keane commented on hpms/pom.xml
> -        <dependency>
This dependency isn't used and pulls in dependencies that are insecure. 
https://mvnrepository.com/artifact/org.projectreactor/reactor-spring/1.0.1.RELEASE

2022-07-21 19:42 UTC, sb-keane commented on api/Dockerfile
> +FROM openjdk:17
New Relic doesn't work with 19 yet.

2022-07-21 20:01 UTC, sharshar-sb requested changes

2022-07-21 20:01 UTC, sharshar-sb commented on eventlogger/pom.xml
> +            <version>42.4.0</version>
It looks like the version is not specified any any of the postgresql dependencies. Create a variable in the top level pom for the version and propagate it down to all the poms.

2022-07-21 20:07 UTC, sb-keane commented on .github/workflows/combine-prs.yml
> +      - uses: actions/github-script@v5
That was a typo. Thanks for catching it!

2022-07-21 20:33 UTC, sharshar-sb approved these changes

2022-07-22 15:05 UTC, sb-dkniesteadt approved these changes

2022-07-22 15:18 UTC, merged