Feature/ab2 d 4882 send event when hpms call fails
CMSgov/ab2d pull request #1075
Opened 2022-08-03 18:50 UTC by sb-keane

**JIRA Tickets:**

[AB2D-4882](https://jira.cms.gov/browse/AB2D-4882) - Description

When HPMS fails authentication send an alert to the AB2D event error table.

### What Does This PR Do?

Adds error handling to HPMS auth code. Previously status code wasn't taken into account when extracting the request's body. These change check for 200 and return an error otherwise. The error is then checked against some know failure scenarios. Uncommon errors get a generic error message and the request's body is logged. 

### What Should Reviewers Watch For?

Opportunities to simplify this code. 

### Usage/Deployment Instructions

### Impacted External Components

### Database Changes

- [X] All QuickSight impacts have been identified

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [X] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [X] Code checked for PHI/PII exposure

2022-08-03 18:57 UTC, sb-keane commented on hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceImpl.java
> +            case (403):
When we fully upgrade to Java 13 these can be replaced with enum values.

2022-08-03 19:04 UTC, sharshar-sb approved these changes

2022-08-03 19:04 UTC, sharshar-sb commented on eventlogger/src/main/java/gov/cms/ab2d/eventlogger/events/ErrorEvent.java
> +        HpMS_AUTH_ERROR
HMPS instead of HpMS

2022-08-03 19:04 UTC, sharshar-sb commented on hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
Interesting - didn't know this one.

2022-08-03 20:07 UTC, sharshar-sb approved these changes

2022-08-03 21:45 UTC, sb-dkniesteadt approved these changes

2022-08-04 23:51 UTC, nflearl requested changes

2022-08-04 23:51 UTC, nflearl commented on common/src/main/java/gov/cms/ab2d/common/util/Constants.java
> +    public static final String HPMS_ORGANIZATION = "HPMS_AUTH";
Why is this defined globally?  This goes very much against what we are trying to do which is to break up the monolith.  It should be either defined in the HPMS module or in the EVENT client jar.

2022-08-04 23:51 UTC, nflearl commented on hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceImpl.java
> +                    if (response.statusCode().equals(OK)) {
tertiary operator would be cleaner, no need for the else clutter.

2022-08-04 23:51 UTC, nflearl commented on hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
Ditto.

2022-08-10 15:19 UTC, nflearl approved these changes

2022-08-10 15:32 UTC, sb-dkniesteadt approved these changes

2022-08-10 16:27 UTC, merged