Feature/ab2d 5182 contract integration
CMSgov/ab2d pull request #1156
Opened 2022-12-16 15:49 UTC by sb-dkniesteadt

**JIRA Tickets:**

[AB2D-5182](https://jira.cms.gov/browse/AB2D-5182) - Integrates the contract service with ab2d (with feature flag)
 
### What Does This PR Do?
Allows ab2d to get contract/update contract data from contract service. By default, it is disabled unless an env variable as it enabled.

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [ ] This PR includes any required documentation changes, (`README`, changelog / release notes, website - see [confluence](https://confluence.cms.gov/display/AB2D/Public+Facing+Documentation) for full list).
- [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [ ] Code checked for PHI/PII exposure

2022-12-20 23:18 UTC, sharshar-sb requested changes
Should the ~Attribution_Report_Sample.xlsx file be there?

2022-12-23 19:54 UTC, sb-keane submitted a review, later dismissed

2023-01-04 17:57 UTC, sb-dkniesteadt commented
> 

Im not seeing Attribution_Report_Sample

2023-01-04 17:57 UTC, sb-dkniesteadt commented
> Should the ~Attribution_Report_Sample.xlsx file be there?

Im not seeing Attribution_Report_Sample

2023-01-05 20:02 UTC, sharshar-sb approved these changes

2023-01-05 20:28 UTC, sb-keane approved these changes

2023-01-05 20:29 UTC, merged