Feature/ab2 d 5289 detect ab2d bfd hpms coverage
CMSgov/ab2d pull request #1181
Opened 2023-01-30 18:36 UTC by sb-keane

**JIRA Tickets:**

[AB2D-5289 ](https://jira.cms.gov/browse/AB2D-5289 ) - Description
Adds sending counts to coverage lambda

 
### What Does This PR Do?

### What Should Reviewers Watch For?

### Usage/Deployment Instructions

### Impacted External Components

### Database Changes

- [ ] All QuickSight impacts have been identified

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [X] This PR includes any required documentation changes, (`README`, changelog / release notes, website - see [confluence](https://confluence.cms.gov/display/AB2D/Public+Facing+Documentation) for full list).
- [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [X] Code checked for PHI/PII exposure

2023-01-30 19:08 UTC, sharshar-sb requested changes

2023-01-30 19:08 UTC, sharshar-sb commented on worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageProcessorImpl.java
> +            coverageSnapshotService.sendCoverageCounts(AB2DServices.BFD, Set.of(contractNumber));
Is this (or should this be) the number beneficiaries retrieved from BFD?

2023-01-30 21:05 UTC, sb-dkniesteadt submitted a review, later dismissed

2023-02-14 20:51 UTC, sharshar-sb approved these changes

2023-02-14 21:08 UTC, sb-dkniesteadt approved these changes

2023-02-14 21:10 UTC, merged