dependabot updates non-breaking
CMSgov/ab2d pull request #509
Opened 2020-11-13 19:51 UTC by wnyffenegger

**JIRA Tickets:**

[AB2D-2653](https://jira.cms.gov/browse/AB2D-42) - Dependabot plugin updates

***Related Tickets***

[AB2D-2458](https://jira.cms.gov/browse/AB2D-2458) - Reason it's related
 
### What Does This PR Do?

Basic set of updates to knock out slice

### What Should Reviewers Watch For?

### Usage/Deployment Instructions

### Impacted External Components

### Database Changes

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [ ] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [ ] Code checked for PHI/PII exposure

2020-11-13 21:35 UTC, lailasharshar approved these changes

2020-11-13 21:41 UTC, nflearl requested changes

2020-11-13 21:41 UTC, nflearl commented on hpms/pom.xml
> +                                            <minimum>85%</minimum>
File a bug for this and comment on the number.

2020-11-16 16:10 UTC, lailasharshar approved these changes

2020-11-16 16:16 UTC, nflearl approved these changes

2020-11-16 16:17 UTC, merged