Clean docker environment after a build
CMSgov/ab2d pull request #537
Opened 2020-12-12 01:42 UTC by lhanekam

**JIRA Tickets:**

[AB2D-2813](https://jira.cms.gov/browse/AB2D-2813) - Clean docker environment on agent after a build

***Related Tickets***

N/A
 
### What Does This PR Do?

Cleans the docker environment on an agent after a build by doing the following:

1. Deletes all docker volumes

2. Deletes all stopped containers

3. Deletes all images except the following

   - postgres:11

   - testcontainers/ryuk:0.3.0

   - testcontainersofficial/ryuk:0.3.0

   - maven:3-jdk-13

   - openjdk:13

   - alpine/socat:1.7.3.4-r0

   - alpine/socat:latest

   - quay.io/testcontainers/ryuk:0.2.3

4. Deletes all docker networks except the following

   - bridge

   - host

   - none

### What Should Reviewers Watch For?

N/A

### Usage/Deployment Instructions

N/A

### Impacted External Components

N/A

### Database Changes

N/A

### Limitations

N/A

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [X] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [X] Code checked for PHI/PII exposure

2020-12-12 01:59 UTC, nflearl submitted a review, later dismissed

2020-12-14 14:01 UTC, wnyffenegger approved these changes

2020-12-14 14:15 UTC, wnyffenegger requested changes
CI build is causing issues on post build changes

2020-12-15 03:34 UTC, nflearl submitted a review, later dismissed
Might want to re-comment the logging back out.

2020-12-15 03:34 UTC, nflearl commented on e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
> +                .withLogConsumer("api", new Slf4jLogConsumer(apiLogger));
Might want to recomment these out.

2020-12-15 16:12 UTC, wnyffenegger submitted a review, later dismissed
I would like to leave the loggers in so we know when an issue has been caused by liquibase and when an issue has been caused by something else in the e2e tests.

2020-12-15 17:15 UTC, nflearl requested changes

2020-12-15 17:15 UTC, nflearl commented on e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
> +                .withLogConsumer("api", new Slf4jLogConsumer(apiLogger));
Quick chat, Will wants to make these semi-permanent.  I'm fine with that.

Comment needs to be made more accurate or deleted.

2020-12-15 17:19 UTC, nflearl approved these changes

2020-12-15 17:44 UTC, lailasharshar approved these changes

2020-12-15 17:45 UTC, merged