Restrict mTLS Trust Policy
CMSgov/ab2d pull request #765
Opened 2021-09-21 17:42 UTC by sb-wnyffenegger

**JIRA Tickets:**

[AB2D-3971](https://jira.cms.gov/browse/AB2D-3971) - Only Trust BFD Cert for BFD HttpClient
 
### What Does This PR Do?

BFD Client now
* No longer trust public certs for the HttpClient
* No longer trust self signed certs by default
* Only certs explicitly added to trust store
* Add unit tests to verify that only certs explicitly added to trust store
* Fix existing tests to use mock ports via property overriding
* Move keystore out of main sources

### What Should Reviewers Watch For?

* Some hoops have to be jumped through for the certs test. Check that these hoops are acceptable.

### Usage/Deployment Instructions

### Impacted External Components

### Database Changes

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [ ] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [ ] Code checked for PHI/PII exposure

2021-09-21 22:22 UTC, nflearl requested changes

2021-09-21 22:22 UTC, nflearl commented on bfd/src/test/java/gov/cms/ab2d/bfd/client/BFDClientConfigurationTest.java
> +    private BFDClientImpl bbc;
Either change to an interface or add a comment describing why the Impl is necessary.

2021-09-22 15:02 UTC, nflearl approved these changes

2021-09-22 19:32 UTC, nflearl approved these changes

2021-09-24 17:49 UTC, sb-benohe approved these changes
Tested in prod-Validation

2021-09-24 18:38 UTC, sharshar-sb approved these changes

2021-09-24 18:40 UTC, merged