Techdebt/ab2d 4124 document enrollment details
CMSgov/ab2d pull request #818
Opened 2021-11-16 17:17 UTC by sb-wnyffenegger

**JIRA Tickets:**

[AB2D-4124](https://jira.cms.gov/browse/AB2D-4124) - Document Enrollment Details in Code
 
### What Does This PR Do?

Code Changes
* 

Documentation

### What Should Reviewers Watch For?

* Documentation that seems unclear or inaccurate and needs to be re-written

### Usage/Deployment Instructions

### Impacted External Components

### Database Changes

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [ ] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [ ] Code checked for PHI/PII exposure

2021-11-18 20:12 UTC, nflearl commented on worker/src/main/resources/application.properties
> +# How often to write out % complete to stdout
Put in the comment what the units are.  Are these msec or something else?

As a future aside, having the name of the property include the units is much clearer.  e.g. report.progress.db.frequency.ms=

2021-11-19 17:08 UTC, sharshar-sb requested changes
Most of my comments are related to clarifying vague words such as "search", "results" or "business requirements". Is it a coverage database search, bfd search, etc.

2021-11-19 17:08 UTC, sharshar-sb commented on worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverImpl.java
> +     * Page through coverage using a provided paging request
When you say "page", it wasn't obvious whether you meant in the database or BFD.

2021-11-19 17:08 UTC, sharshar-sb commented on worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverImpl.java
> +     *      - Filtered contracts {@link CoveragePeriodsPresentCheck}
Filtered contracts?

2021-11-19 22:11 UTC, sb-dkniesteadt approved these changes

2021-11-22 22:59 UTC, sharshar-sb approved these changes

2021-11-23 18:25 UTC, merged