Updated organization and attestation endpoints to v2
CMSgov/ab2d pull request #884
Opened 2022-01-13 21:34 UTC by sb-keane

**JIRA Tickets:**
AB2D-4235

Description
Updates the organization info and attestation endpoints to v2. The ACS value was moved to a cookie instead of a url parameter. 

***Related Tickets***
None
 
### What Does This PR Do?
Updates the existing code to work with v2 endpoints instead of the original endpoints. 

### What Should Reviewers Watch For?
Incomplete data mapping of v2 with out data model

### Usage/Deployment Instructions
Standard process

### Impacted External Components

### Database Changes

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [X] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [X] Code checked for PHI/PII exposure

2022-01-14 17:50 UTC, SB-JChacko approved these changes

2022-01-14 19:16 UTC, sb-dkniesteadt approved these changes

2022-01-14 22:44 UTC, nflearl requested changes
Overall, a really nice job.  I just found a few nits that should be trivial to fix.

2022-01-14 22:44 UTC, nflearl commented on hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceTest.java
> +
Don't see a need for this especially in the AuthService which should be standalone.

2022-01-14 22:44 UTC, nflearl commented on hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceImpl.java
> +                .exchangeToFlux(r -> {
I have no idea what an r is.  Please give the lambda variable a more meaningful name.

2022-01-14 22:44 UTC, nflearl commented on hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceImpl.java
> +                        .map(v -> cookie.getKey() + "=" + v.getValue()))
Likewise, I have no idea what a v is.  Please give the lambda variable a more meaningful name.

2022-01-18 18:53 UTC, nflearl approved these changes

2022-01-18 18:53 UTC, nflearl approved these changes

2022-01-21 21:27 UTC, merged