Updated header for file so that it doesn't error out with swagger
CMSgov/ab2d pull request #903
Opened 2022-01-26 21:29 UTC by sharshar-sb

**JIRA Tickets:**

[AB2D-4332](https://jira.cms.gov/browse/AB2D-4332) - The new swagger errors out when you try to download the files

### What Does This PR Do?

Updates response header to give swagger instructions. It prevents it from hanging and allows users to download the file with a click

### What Should Reviewers Watch For?

There should be no impact for other clients

### Usage/Deployment Instructions

Deploy to sandbox

### Impacted External Components

### Database Changes

### Limitations

### Security Implications

- [ ] This PR adds new software dependencies
- [ ] This PR modifies or invalidates our security controls
- [ ] This PR stores or transmits data that was not stored or transmitted before

- [ ] This PR requires additional review of its security implications for other reasons

### What Needs to Be Merged and Deployed Before this PR?

### Submitter Checklist

- [ ] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.
- [ ] Code checked for PHI/PII exposure

2022-01-26 22:07 UTC, sb-benohe requested changes

2022-01-26 22:07 UTC, sb-benohe commented on api/src/main/java/gov/cms/ab2d/api/controller/common/FileDownloadCommon.java
> +        response.setHeader("Content-Disposition", "inline; swaggerDownload=\"attachment\"; filename=\"" + filename + "\"");
Can you give me a day or two to look in to how this will affect other downloads

2022-01-28 21:26 UTC, sb-wnyffenegger approved these changes

2022-01-31 19:01 UTC, sb-keane approved these changes

2022-01-31 20:00 UTC, sb-benohe approved these changes

2022-02-01 16:04 UTC, merged